cart_icon_loc = '//span[text()="My Cart"]'
empty_cart_icon_loc = '//strong[text()="You have no items in your shopping cart."]'
not_empty_cart_icon_loc = '//*[contains(@class, "counter-number")]'
product_loc = '.product-item'
product_size_loc = '//*[@aria-describedby="option-label-size-143"]'
product_color_loc = '//*[@aria-describedby="option-label-color-93"]'
add_to_cart_button_loc = '//button[@title="Add to Cart"]'
add_to_compare_loc = '.tocompare'
added_to_compare_message_loc = '//*[contains(@data-bind, "prepareMessageForHtml")]'
compare_section_loc = 'div.sidebar.sidebar-additional'
product_in_compare_loc = '//*[@id="compare-items"]'
